<!DOCTYPE html>
<html lang="en"><head> 
<meta charset="UTF-8">
<meta name="description" content="chess tournament">
<meta name="author" content="www.vegachess.com">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge"> 
<title>2025 Hobsons Bay Chess Club Best in The West</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<link rel="stylesheet" href="stylenew.css" type="text/css" >
    </head>
<body>
<div class="d-flex flex-column justify-content-between h-100">
 <nav class="navbar navbar-expand-lg fixed-top">
                <div class="container">    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0"><li class="nav-item dropdown">
   <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Info</a>
<ul class="dropdown-menu">
<li><a class="dropdown-item" href="schedule.php"> Schedule </a></li><li><a class="dropdown-item" href="tourstat.php">Statistics</a></li> </ul></li><li class="nav-item dropdown">   <a class="nav-link" href="index.php" >Players</a>
</li><li class="nav-item"><a class="nav-link " href="pairs5.php" >Pairings</a>
</li><li class="nav-item"><a class="nav-link" href="standings.php" >Standings</a>
</li><li class="nav-item dropdown">   <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Tables</a>
<ul class="dropdown-menu"><li><a class="dropdown-item" href="crosstable.php"> Cross table </a></li><li><a class="dropdown-item" href="crosstablescore.php"> Cross table and standings </a></li><li><a class="dropdown-item" href="rankinggroup.php"> Standings by Rtg groups </a></li><li><a class="dropdown-item" href="rankingagegroup.php"> Standings by age groups </a></li><li><a class="dropdown-item" href="rankcat.php"> Standings by title </a></li><li><a class="dropdown-item" href="rankTeams.php"> Rank Teams </a></li><li><a class="dropdown-item" href="summaryFederations.php"> Summary Federations </a></li><li><a class="dropdown-item" href="summaryOrigin.php"> Summary Origin </a></li></ul></li><li class="nav-item"><a class="nav-link" href="games.php" >Games</a>
</li><li class="nav-item dropdown">   <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Reports</a>
<ul class="dropdown-menu">          <li><a class="dropdown-item" href="felovar.php">FIDE Rating</a></li>          <li><a class="dropdown-item" href="fideplayercard.php">FIDE Player Card</a></li>           <li><a class="dropdown-item" href="nelovar.php">National rating</a></li>          <li><a class="dropdown-item" href="playercard.php">National Player Card</a></li></ul></li></ul> </div>
</div>
</nav>
 <section id="hero" class="d-flex align-items-center">
                <div class="container-fluid">
                    <div class="row items-center">
                        <div class="col-12">
                            <div class="flex flex-column justify-content-center text-center text-white">			<h1 class="mb-3" style="text-shadow: 2px 2px 4px #000000;" >2025 Hobsons Bay Chess Club Best in The West</h1>		    <h5 class="mb-1">Hobsons Bay Chess Club (AUS)</h5>		    <h5> 30/08/2025 - 31/08/2025</h5>   </div>
 </div> 
 </div>
 </div> 
 </section>
 <section id="main" class="pt-3 mb-auto">
                <div class="container-fluid">
                    <div class="row">
                        <div class="d-none d-lg-block col-1 ps-0">
                            <div class="d-flex flex-column w-full overflow-hidden"> </div> </div> <div class="col-12 col-lg-10">
  <div class="d-flex flex-column"> <div class="btn-toolbar mb-4 mt-4 d-flex align-items-center"> 
<h5>Pairing of round 3</h5>
   	<div class="btn-group mx-5"> 
<?php include("pairing.php"); ?>
   	</div>
 </div>
<div class="table-responsive"><table class="table table-sm table-striped"> 
<thead><tr><th>Bo.</th><th>Fed</th><th>Origin</th><th>White Player</th><th>Pts</th><th>Result</th><th>Pts</th><th>Black Player</th><th>Origin</th><th>Fed</th></tr></thead><tbody>
<tr> <td>1</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 1 </span><span class="title male"> IM</span> <a href="playercard.php#1"> Morris,James</a> </td><td>2</td><td class="result">1 - 0</td><td>2</td><td class="name"><span class="idblack">12 </span><span class="notitle male"> </span> <a href="playercard.php#12"> Hogg,Dean</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>2</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 14 </span><span class="notitle male"> </span> <a href="playercard.php#14"> Smith,Jack</a> </td><td>2</td><td class="result">0 - 1</td><td>2</td><td class="name"><span class="idblack">2 </span><span class="title male"> FM</span> <a href="playercard.php#2"> Soo,Kai Jie</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>3</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 3 </span><span class="title male"> FM</span> <a href="playercard.php#3"> Dai,Cheng</a> </td><td>2</td><td class="result">1 - 0</td><td>2</td><td class="name"><span class="idblack">16 </span><span class="notitle male"> </span> <a href="playercard.php#16"> Zheng,Ryan</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>4</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 17 </span><span class="title female"> WFM</span> <a href="playercard.php#17"> Chibnall,Alana</a> </td><td>2</td><td class="result">0 - 1</td><td>2</td><td class="name"><span class="idblack">4 </span><span class="title male"> FM</span> <a href="playercard.php#4"> Dragicevic,Domagoj</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>5</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 5 </span><span class="title male"> CM</span> <a href="playercard.php#5"> Annapureddy,Rheyansh Reddy</a> </td><td>2</td><td class="result">1 - 0</td><td>2</td><td class="name"><span class="idblack">18 </span><span class="notitle male"> </span> <a href="playercard.php#18"> Herlihy,Brian</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>6</td><td><img class="shadow" src="flag/qld.png" "> QLD</td><td></td><td class="name"> <span class="idwhite"> 20 </span><span class="notitle male"> </span> <a href="playercard.php#20"> Shen,Owen</a> </td><td>2</td><td class="result">½ - ½</td><td>2</td><td class="name"><span class="idblack">6 </span><span class="title male"> FM</span> <a href="playercard.php#6"> Yang,Ray</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>7</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 7 </span><span class="title male"> CM</span> <a href="playercard.php#7"> Thogata,Randheer</a> </td><td>2</td><td class="result">1 - 0</td><td>2</td><td class="name"><span class="idblack">22 </span><span class="notitle male"> </span> <a href="playercard.php#22"> Lim,Jongmin</a></td><td></td><td><img class="shadow" src="flag/nsw.png" "> NSW</td></tr>
<tr> <td>8</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 23 </span><span class="notitle male"> </span> <a href="playercard.php#23"> Lingineni,Khushal</a> </td><td>2</td><td class="result">0 - 1</td><td>2</td><td class="name"><span class="idblack">8 </span><span class="title male"> CM</span> <a href="playercard.php#8"> Gao,Arthur</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>9</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 9 </span><span class="title male"> CM</span> <a href="playercard.php#9"> Hartley,James</a> </td><td>2</td><td class="result">1 - 0</td><td>2</td><td class="name"><span class="idblack">24 </span><span class="notitle male"> </span> <a href="playercard.php#24"> Buhagiar,Aden</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>10</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 26 </span><span class="notitle male"> </span> <a href="playercard.php#26"> Hari,Dhruv</a> </td><td>2</td><td class="result">0 - 1</td><td>2</td><td class="name"><span class="idblack">10 </span><span class="title male"> CM</span> <a href="playercard.php#10"> Smith,Declan</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>11</td><td><img class="shadow" src="flag/ind.png" "> IND</td><td></td><td class="name"> <span class="idwhite"> 103 </span><span class="notitle male"> </span> <a href="playercard.php#103"> Venkatesan,Sudharsun</a> </td><td>1.5</td><td class="result">0 - 1</td><td>2</td><td class="name"><span class="idblack">45 </span><span class="notitle male"> </span> <a href="playercard.php#45"> Bodke,Krishna</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>12</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 15 </span><span class="title male"> CM</span> <a href="playercard.php#15"> Davis,Tony J</a> </td><td>1</td><td class="result">0 - 1</td><td>1.5</td><td class="name"><span class="idblack">31 </span><span class="notitle male"> </span> <a href="playercard.php#31"> Nguyen,Anh Kiet</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>13</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 27 </span><span class="notitle male"> </span> <a href="playercard.php#27"> Ogden,Marcus W</a> </td><td>1</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">52 </span><span class="notitle male"> </span> <a href="playercard.php#52"> Lees,Dane</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>14</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 54 </span><span class="notitle male"> </span> <a href="playercard.php#54"> Wilkinson,Greg</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">28 </span><span class="title female"> WIM</span> <a href="playercard.php#28"> Szuveges,Narelle S</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>15</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 29 </span><span class="notitle male"> </span> <a href="playercard.php#29"> Rodriguez,Maickel</a> </td><td>1</td><td class="result">½ - ½</td><td>1</td><td class="name"><span class="idblack">53 </span><span class="notitle male"> </span> <a href="playercard.php#53"> Ramanathan,Ashwin</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>16</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 60 </span><span class="notitle male"> </span> <a href="playercard.php#60"> Batyrbekov,Kaisar</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">30 </span><span class="notitle male"> </span> <a href="playercard.php#30"> Tanner,Jonathan</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>17</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 32 </span><span class="notitle male"> </span> <a href="playercard.php#32"> Li,LiYuan</a> </td><td>1</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">61 </span><span class="notitle male"> </span> <a href="playercard.php#61"> Laffey,Julian</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>18</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 66 </span><span class="notitle male"> </span> <a href="playercard.php#66"> Ha,Aeson</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">33 </span><span class="notitle female"> </span> <a href="playercard.php#33"> Davis,Sophie</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>19</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 34 </span><span class="notitle male"> </span> <a href="playercard.php#34"> Hogan,Steven</a> </td><td>1</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">63 </span><span class="notitle male"> </span> <a href="playercard.php#63"> Ngo,William</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>20</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 70 </span><span class="notitle male"> </span> <a href="playercard.php#70"> Batyrbekov,Aidan</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">35 </span><span class="notitle male"> </span> <a href="playercard.php#35"> Humphreys,Scott</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>21</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 36 </span><span class="notitle male"> </span> <a href="playercard.php#36"> Ruaya,Chris Rodson</a> </td><td>1</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">65 </span><span class="notitle female"> </span> <a href="playercard.php#65"> Yates,Anna</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>22</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 72 </span><span class="notitle male"> </span> <a href="playercard.php#72"> Balaji,Sai Sivesh</a> </td><td>1</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">37 </span><span class="notitle male"> </span> <a href="playercard.php#37"> Nowak,Ruben</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>23</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 38 </span><span class="notitle male"> </span> <a href="playercard.php#38"> Picone,James</a> </td><td>1</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">67 </span><span class="notitle male"> </span> <a href="playercard.php#67"> Ashok,Arjun</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>24</td><td><img class="shadow" src="flag/ban.png" "> BAN</td><td></td><td class="name"> <span class="idwhite"> 74 </span><span class="notitle male"> </span> <a href="playercard.php#74"> Ahmad,Ihtiram</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">39 </span><span class="notitle male"> </span> <a href="playercard.php#39"> Hu,Tony</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>25</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 40 </span><span class="notitle male"> </span> <a href="playercard.php#40"> Rehill,Paul</a> </td><td>1</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">69 </span><span class="notitle male"> </span> <a href="playercard.php#69"> Jagannathan,Shashvath</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>26</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 42 </span><span class="notitle male"> </span> <a href="playercard.php#42"> Windsor,Maximilian</a> </td><td>1</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">71 </span><span class="notitle male"> </span> <a href="playercard.php#71"> Zhang,Chi Long</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>27</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 44 </span><span class="notitle male"> </span> <a href="playercard.php#44"> Tsagarakis,Angelo</a> </td><td>1</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">77 </span><span class="notitle male"> </span> <a href="playercard.php#77"> Wales,Sam</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>28</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 46 </span><span class="notitle male"> </span> <a href="playercard.php#46"> Tang,Fergus</a> </td><td>1</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">83 </span><span class="notitle male"> </span> <a href="playercard.php#83"> Arora,Daanish</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>29</td><td><img class="shadow" src="flag/qld.png" "> QLD</td><td></td><td class="name"> <span class="idwhite"> 86 </span><span class="notitle male"> </span> <a href="playercard.php#86"> Black,Nick</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">47 </span><span class="notitle male"> </span> <a href="playercard.php#47"> Parker,Lucas</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>30</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 48 </span><span class="notitle male"> </span> <a href="playercard.php#48"> Annapureddy,Dhruthin Reddy</a> </td><td>1</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">85 </span><span class="notitle male"> </span> <a href="playercard.php#85"> Bakker,Andrew</a></td><td></td><td><img class="shadow" src="flag/tas.png" "> TAS</td></tr>
<tr> <td>31</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 100 </span><span class="notitle male"> </span> <a href="playercard.php#100"> Shahadat,Aladean</a> </td><td>1</td><td class="result">0 - 1</td><td>1</td><td class="name"><span class="idblack">49 </span><span class="notitle female"> </span> <a href="playercard.php#49"> Scenna,Luna</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>32</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 50 </span><span class="notitle male"> </span> <a href="playercard.php#50"> Brockman,Roland</a> </td><td>1</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">91 </span><span class="notitle male"> </span> <a href="playercard.php#91"> Kitonga,Jack</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>33</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 51 </span><span class="notitle male"> </span> <a href="playercard.php#51"> Yang,Yifan</a> </td><td>0.5</td><td class="result">1 - 0</td><td>1</td><td class="name"><span class="idblack">104 </span><span class="notitle male"> </span> <a href="playercard.php#104"> Vignesh,Prajeeth Balaji</a></td><td></td><td><img class="shadow" src="flag/nzl.png" "> NZL</td></tr>
<tr> <td>34</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 81 </span><span class="notitle female"> </span> <a href="playercard.php#81"> Husain,Lamiah</a> </td><td>0.5</td><td class="result">0 - 1</td><td>0.5</td><td class="name"><span class="idblack">75 </span><span class="notitle female"> </span> <a href="playercard.php#75"> Warren,Elizabeth</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>35</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 102 </span><span class="notitle male"> </span> <a href="playercard.php#102"> Vemula,Thamoghna</a> </td><td>0.5</td><td class="result">1 - 0</td><td>0.5</td><td class="name"><span class="idblack">82 </span><span class="notitle male"> </span> <a href="playercard.php#82"> Lim,Darren</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>36</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 58 </span><span class="notitle male"> </span> <a href="playercard.php#58"> Huang,Joshua Kai-En</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">93 </span><span class="notitle male"> </span> <a href="playercard.php#93"> Moser,William</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>37</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 64 </span><span class="notitle male"> </span> <a href="playercard.php#64"> Scenna,George</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">97 </span><span class="notitle male"> </span> <a href="playercard.php#97"> Samraat,Aayush</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>38</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 68 </span><span class="notitle female"> </span> <a href="playercard.php#68"> Wang,Adelyn</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">99 </span><span class="notitle male"> </span> <a href="playercard.php#99"> Saravanakumar,Thaswin</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>39</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 90 </span><span class="notitle male"> </span> <a href="playercard.php#90"> Gupta,Riaan</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">73 </span><span class="notitle male"> </span> <a href="playercard.php#73"> Ruaya,Rohan</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>40</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 92 </span><span class="notitle male"> </span> <a href="playercard.php#92"> Moser,Luke</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">80 </span><span class="notitle male"> </span> <a href="playercard.php#80"> Shaiek,Nihal</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>41</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 84 </span><span class="notitle male"> </span> <a href="playercard.php#84"> Arun,Devsankar</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">101 </span><span class="notitle male"> </span> <a href="playercard.php#101"> Sharma,Rudra</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>42</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 96 </span><span class="notitle male"> </span> <a href="playercard.php#96"> Palta,Sameer</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">87 </span><span class="notitle female"> </span> <a href="playercard.php#87"> Chapnevis,Elmira</a></td><td></td><td><img class="shadow" src="flag/iri.png" "> IRI</td></tr>
<tr> <td>43</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 88 </span><span class="notitle male"> </span> <a href="playercard.php#88"> Denny,William</a> </td><td>0</td><td class="result">0 - 1</td><td>0</td><td class="name"><span class="idblack">106 </span><span class="notitle male"> </span> <a href="playercard.php#106"> Yegnavajjula,Aryan Srivatsav</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>44</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 98 </span><span class="notitle male"> </span> <a href="playercard.php#98"> Samrat,Avyay</a> </td><td>0</td><td class="result">1 - 0</td><td>0</td><td class="name"><span class="idblack">89 </span><span class="notitle male"> </span> <a href="playercard.php#89"> Gowda,Likhil</a></td><td></td><td><img class="shadow" src="flag/vic.png" "> VIC</td></tr>
<tr> <td>45</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 105 </span><span class="notitle male"> </span> <a href="playercard.php#105"> Vigneshwar,Krishanth</a> </td><td>0</td><td class="result">1    </td><td>0</td><td class="name">( bye )</td><td></td><td></td></tr>
<tr> <td>46</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 11 </span><span class="notitle male"> </span> <a href="playercard.php#11"> Milojevic,Miodrag</a> </td><td>2</td><td class="result">½    </td><td>0</td><td class="name">( half point bye )</td><td></td><td></td></tr>
<tr> <td>47</td><td><img class="shadow" src="flag/nsw.png" "> NSW</td><td></td><td class="name"> <span class="idwhite"> 21 </span><span class="notitle male"> </span> <a href="playercard.php#21"> Kumar,Viney</a> </td><td>2</td><td class="result">½    </td><td>0</td><td class="name">( half point bye )</td><td></td><td></td></tr>
<tr> <td>48</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 25 </span><span class="notitle male"> </span> <a href="playercard.php#25"> Ilic,Goran</a> </td><td>2</td><td class="result">½    </td><td>0</td><td class="name">( half point bye )</td><td></td><td></td></tr>
<tr> <td>49</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 13 </span><span class="notitle male"> </span> <a href="playercard.php#13"> Savige,Colin B</a> </td><td>1.5</td><td class="result">½    </td><td>0</td><td class="name">( half point bye )</td><td></td><td></td></tr>
<tr> <td>50</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 43 </span><span class="notitle male"> </span> <a href="playercard.php#43"> Cauchi,John-Paul</a> </td><td>1.5</td><td class="result">½    </td><td>0</td><td class="name">( half point bye )</td><td></td><td></td></tr>
<tr> <td>51</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 41 </span><span class="notitle male"> </span> <a href="playercard.php#41"> Whitford,Matthew</a> </td><td>1</td><td class="result">½    </td><td>0</td><td class="name">( half point bye )</td><td></td><td></td></tr>
<tr> <td>52</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 57 </span><span class="notitle female"> </span> <a href="playercard.php#57"> Zhou,Emma</a> </td><td>1</td><td class="result">½    </td><td>0</td><td class="name">( half point bye )</td><td></td><td></td></tr>
<tr> <td>53</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 62 </span><span class="notitle male"> </span> <a href="playercard.php#62"> Gurkan,Ahmet</a> </td><td>1</td><td class="result">½    </td><td>0</td><td class="name">( half point bye )</td><td></td><td></td></tr>
<tr> <td>54</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 76 </span><span class="notitle male"> </span> <a href="playercard.php#76"> Zhou,Teng</a> </td><td>1</td><td class="result">½    </td><td>0</td><td class="name">( half point bye )</td><td></td><td></td></tr>
<tr> <td>55</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 95 </span><span class="notitle male"> </span> <a href="playercard.php#95"> Nema,Nivaan</a> </td><td>1</td><td class="result">½    </td><td>0</td><td class="name">( half point bye )</td><td></td><td></td></tr>
<tr> <td>56</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 55 </span><span class="notitle male"> </span> <a href="playercard.php#55"> Gurkan,Mehmet</a> </td><td>0.5</td><td class="result">½    </td><td>0</td><td class="name">( half point bye )</td><td></td><td></td></tr>
<tr> <td>57</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 56 </span><span class="notitle male"> </span> <a href="playercard.php#56"> Thompson,Selby</a> </td><td>0.5</td><td class="result">½    </td><td>0</td><td class="name">( half point bye )</td><td></td><td></td></tr>
<tr> <td>58</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 19 </span><span class="notitle female"> </span> <a href="playercard.php#19"> Venkat,Nyra</a> </td><td>0</td><td class="result">½    </td><td>0</td><td class="name">( half point bye )</td><td></td><td></td></tr>
<tr> <td>59</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 59 </span><span class="notitle male"> </span> <a href="playercard.php#59"> Sheth,Adidev</a> </td><td>0</td><td class="result">½    </td><td>0</td><td class="name">( half point bye )</td><td></td><td></td></tr>
<tr> <td>60</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 79 </span><span class="notitle male"> </span> <a href="playercard.php#79"> Verma,Vivaan</a> </td><td>0</td><td class="result">½    </td><td>0</td><td class="name">( half point bye )</td><td></td><td></td></tr>
<tr> <td>61</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 78 </span><span class="notitle female"> </span> <a href="playercard.php#78"> Tan,Mia</a> </td><td>0.5</td><td class="result">0    </td><td>0</td><td class="name">( not paired )</td><td></td><td></td></tr>
<tr> <td>62</td><td><img class="shadow" src="flag/vic.png" "> VIC</td><td></td><td class="name"> <span class="idwhite"> 94 </span><span class="notitle female"> </span> <a href="playercard.php#94"> Nandi,Jisha</a> </td><td>0.5</td><td class="result">0    </td><td>0</td><td class="name">( not paired )</td><td></td><td></td></tr>
</tbody>
</table>
</DIV><hr>
		  </div>
		      </div>
         <div class="d-none d-lg-block col-1 pe-0">
           <div class="d-flex flex-column w-full overflow-hidden">
   </div> </div>  </div>  </div> </section>
    <footer id="footer" class="bg-light py-5 mt-5 border-bottom border-light-subtle border-5">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="d-flex flex-column align-items-center text-center text-dark"><p><a href="http://www.vegachess.com" target="_blank">Generated by Vega</a> All rights reserved</p><p>(Arbiter/Club : Casey Goh - AUS)
  <?php if (file_exists($_SERVER['DOCUMENT_ROOT'].'/siteprivacy.php')) include($_SERVER['DOCUMENT_ROOT'].'/siteprivacy.php'); ?>    </div>  </div>  </div> </div> 
   </footer>
     </div>
       <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script></body>
</html>