name: Reprocess All Tournament Data

on:
  workflow_dispatch: # Manual trigger only
    inputs:
      confirm_reprocess:
        description: 'Type "REPROCESS" to confirm reprocessing all tournament data'
        required: true
        type: string

jobs:
  reprocess-all:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'pnpm'
    
    - name: Install dependencies and link CLI
      run: |
        pnpm install
        pnpm run link-all
    
    - name: Configure Git
      run: |
        git config --global user.name "VegaShare Bot"
        git config --global user.email "vegashare-bot@noreply.github.com"
    
    - name: Validate confirmation
      run: |
        if [ "${{ github.event.inputs.confirm_reprocess }}" != "REPROCESS" ]; then
          echo "❌ Invalid confirmation. Please type 'REPROCESS' to confirm."
          exit 1
        fi
        echo "✅ Confirmation validated. Starting reprocess of all tournament data..."
    
    - name: Check for www directory
      run: |
        echo "🔍 Checking for www directory..."
        if [ -d "www" ]; then
          echo "✅ www directory found"
          echo "📁 Contents: $(ls -la www/ | head -10)"
        else
          echo "❌ www directory not found - nothing to reprocess"
          exit 1
        fi
    
    - name: Reprocess all tournaments
      env:
        TURSO_DATABASE_URL: ${{ secrets.TURSO_DATABASE_URL }}
        TURSO_AUTH_TOKEN: ${{ secrets.TURSO_AUTH_TOKEN }}
      run: |
        echo "🔄 Starting reprocess of all tournament data..."
        
        # Use the new process-folder command to process all www* folders
        vega-cli process-folder --input www --verbose
        
        echo "🔄 Upserting all processed data to database..."
        
        # Find all generated JSON files and upsert them
        JSON_FILES=$(find www -name "data_clean.json" | sort)
        
        if [ -z "$JSON_FILES" ]; then
          echo "ℹ️ No JSON files found to upsert"
          exit 0
        fi
        
        echo "📂 Found JSON files to upsert:"
        echo "$JSON_FILES"
        
        # Upsert each JSON file
        echo "$JSON_FILES" | while read -r jsonFile; do
          if [ -n "$jsonFile" ]; then
            echo "💾 Upserting to database: $jsonFile"
            vega-cli upsert-db --file "$jsonFile" --verbose
            echo "✅ Upserted: $jsonFile"
          fi
        done
        
        echo "✅ All tournaments reprocessed and upserted successfully"
    
    - name: Check for changes
      id: check-changes
      run: |
        echo "🔍 Checking for git changes..."
        
        # Show detailed git status
        echo "📊 Full git status:"
        git status --porcelain || echo "❌ Git status failed"
        
        # Check if there are any changes
        if [ -n "$(git status --porcelain)" ]; then
          echo "✅ Changes detected"
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "ℹ️ No changes detected"
          echo "changes=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.check-changes.outputs.changes == 'true'
      run: |
        git add www/
        git commit -m "Reprocess All: Regenerate JSON and upsert all tournament data
        
        - Reprocessed all tournament folders in www/
        - Regenerated JSON data from HTML files
        - Upserted all tournament data to database
        - Manual reprocess triggered by user
        - Timestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
        - Workflow: ${{ github.workflow }}
        - Run ID: ${{ github.run_id }}"
        git push origin main
    
    - name: Log completion
      run: |
        if [ "${{ steps.check-changes.outputs.changes }}" == "true" ]; then
          echo "✅ Reprocess completed successfully:"
          echo "  - All tournament folders in www/ reprocessed"
          echo "  - JSON data regenerated from HTML files"
          echo "  - All tournament data upserted to database"
          echo "  - Changes committed and pushed"
        else
          echo "ℹ️ No changes detected during reprocess"
        fi
