name: Test Sync (Manual)

on:
  workflow_dispatch:
    inputs:
      seconds:
        description: 'Time window in seconds to check for changes'
        required: false
        default: '300'
        type: string

jobs:
  test-sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'pnpm'
    
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    
    - name: Install dependencies and link CLI
      run: |
        pnpm install
        pnpm run link-all
    
    - name: Configure Git
      run: |
        git config --global user.name "VegaShare Bot"
        git config --global user.email "vegashare-bot@noreply.github.com"
    
    - name: Test sync with custom time window
      run: |
        echo "Testing sync with ${{ github.event.inputs.seconds }} seconds time window..."
        vega-cli check-update --extract --url "https://vegaftp.free.nf/?i=1&seconds=${{ github.event.inputs.seconds }}"
    
    - name: Check for changes
      id: check-changes
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "Files changed:"
          git status --porcelain
        else
          echo "changes=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        fi
    
    - name: Commit and push changes
      if: steps.check-changes.outputs.changes == 'true'
      run: |
        git add .
        git commit -m "Test sync: Update files from remote server
        
        - Time window: ${{ github.event.inputs.seconds }} seconds
        - Timestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')
        - Workflow: ${{ github.workflow }}
        - Run ID: ${{ github.run_id }}"
        git push origin main
    
    - name: Log completion
      run: |
        if [ "${{ steps.check-changes.outputs.changes }}" == "true" ]; then
          echo "✅ Files synced and committed successfully"
        else
          echo "ℹ️ No changes detected, skipping commit"
        fi
