name: Trigger Sync Workflows

on:
  workflow_dispatch:
    inputs:
      trigger_type:
        description: 'Type of sync to trigger'
        required: true
        default: 'auto'
        type: choice
        options:
          - auto
          - html
          - both
      force_trigger:
        description: 'Force trigger even if no changes detected'
        required: false
        default: false
        type: boolean

jobs:
  check-and-trigger:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
      pull-requests: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Check for changes
      id: check-changes
      run: |
        echo "🔍 Checking for changes in the last 5 minutes..."
        
        # Check for changes in vega/ folder (PHP files)
        VEGA_CHANGES=$(git log --since="5 minutes ago" --name-only --pretty=format: | grep -E "^vega/.*\.php$" | wc -l)
        echo "📁 PHP files changed in vega/: $VEGA_CHANGES"
        
        # Also check if vega directory exists and has PHP files
        if [ -d "vega" ]; then
          VEGA_PHP_FILES=$(find vega -name "*.php" -type f | wc -l)
          echo "📄 Current PHP files in vega/: $VEGA_PHP_FILES"
        else
          echo "⚠️  Vega directory does not exist yet"
        fi
        
        # Check for changes in www/ folder (HTML files)
        WWW_CHANGES=$(git log --since="5 minutes ago" --name-only --pretty=format: | grep -E "^www/.*\.html$" | wc -l)
        echo "🌐 HTML files changed in www/: $WWW_CHANGES"
        
        # Check for any changes in the last 5 minutes
        ANY_CHANGES=$(git log --since="5 minutes ago" --oneline | wc -l)
        echo "📝 Total commits in last 5 minutes: $ANY_CHANGES"
        
        # Set outputs
        echo "vega_changes=$VEGA_CHANGES" >> $GITHUB_OUTPUT
        echo "www_changes=$WWW_CHANGES" >> $GITHUB_OUTPUT
        echo "any_changes=$ANY_CHANGES" >> $GITHUB_OUTPUT
        
        # Determine if we should trigger workflows
        SHOULD_TRIGGER_AUTO="false"
        SHOULD_TRIGGER_HTML="false"
        
        if [ "${{ inputs.force_trigger }}" = "true" ]; then
          echo "🚀 Force trigger enabled - will trigger all workflows"
          SHOULD_TRIGGER_AUTO="true"
          SHOULD_TRIGGER_HTML="true"
        else
          if [ "$ANY_CHANGES" -gt 0 ]; then
            echo "✅ Changes detected - will trigger auto-sync"
            SHOULD_TRIGGER_AUTO="true"
          fi
          
          if [ "$VEGA_CHANGES" -gt 0 ]; then
            echo "✅ PHP changes detected - will trigger HTML sync"
            SHOULD_TRIGGER_HTML="true"
          fi
        fi
        
        echo "should_trigger_auto=$SHOULD_TRIGGER_AUTO" >> $GITHUB_OUTPUT
        echo "should_trigger_html=$SHOULD_TRIGGER_HTML" >> $GITHUB_OUTPUT
        
        echo "📊 Summary:"
        echo "  - Auto-sync: $SHOULD_TRIGGER_AUTO"
        echo "  - HTML-sync: $SHOULD_TRIGGER_HTML"
    
    - name: Trigger Auto Sync
      if: steps.check-changes.outputs.should_trigger_auto == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          console.log('🚀 Triggering auto-sync workflow...');
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'auto-sync.yml',
            ref: context.ref
          });
          console.log('✅ Auto-sync workflow triggered successfully');
    
    - name: Trigger HTML Sync
      if: steps.check-changes.outputs.should_trigger_html == 'true'
      uses: actions/github-script@v7
      with:
        script: |
          console.log('🚀 Triggering HTML sync workflow...');
          await github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'sync-html.yml',
            ref: context.ref
          });
          console.log('✅ HTML sync workflow triggered successfully');
    
    - name: No changes detected
      if: steps.check-changes.outputs.should_trigger_auto == 'false' && steps.check-changes.outputs.should_trigger_html == 'false'
      run: |
        echo "ℹ️ No changes detected in the last 5 minutes"
        echo "💡 Use 'force_trigger: true' to trigger workflows anyway"
